export const metadata = {
    title: "Terms of Service | Lawn.Calc",
    description: "Terms and conditions for using the Lawn.Calc Valuation Engine.",
};

export default function TermsOfService() {
    return (
        <div className="max-w-3xl mx-auto px-4 py-12 md:py-20 prose prose-gray prose-headings:text-[var(--secondary)] prose-a:text-[var(--primary)]">
            <h1 className="text-4xl font-black mb-8">Terms of Service</h1>
            <p className="text-sm text-gray-500 mb-8">Last Updated: February 2025</p>

            <h2>1. Introduction</h2>
            <p>
                Welcome to Lawn.Calc! By accessing our website, you agree to be bound by these Terms of Service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws.
            </p>

            <h2>2. Disclaimer of Accuracy</h2>
            <p>
                <strong>The quotes generated by Lawn.Calc are estimates only.</strong> They are based on national averages and algorithmic calculations. Actual service prices may vary based on provider availability, specific local conditions, and physical property inspections.
            </p>
            <p>
                We do not guarantee that any service provider will honor the prices generated by our calculator.
            </p>

            <h2>3. Use License</h2>
            <p>
                Permission is granted to temporarily download one copy of the materials (information or software) on Lawn.Calc's website for personal, non-commercial transitory viewing only.
            </p>
            <ul>
                <li>You may not modify or copy the materials;</li>
                <li>You may not use the materials for any commercial purpose;</li>
                <li>You may not attempt to decompile or reverse engineer any software contained on Lawn.Calc's website;</li>
            </ul>

            <h2>4. Limitations</h2>
            <p>
                In no event shall Lawn.Calc or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Lawn.Calc's website.
            </p>

            <h2>5. Revisions and Errata</h2>
            <p>
                The materials appearing on Lawn.Calc's website could include technical, typographical, or photographic errors. Lawn.Calc does not warrant that any of the materials on its website are accurate, complete, or current.
            </p>

            <h2>6. Governing Law</h2>
            <p>
                These terms and conditions are governed by and construed in accordance with the laws of the United States and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
            </p>
        </div>
    );
}
